# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-the-app:
    docker:
      # specify the version you desire here
      - image: circleci/node:10
      # Specify service dependencies here if necessary.
      # CircleCI maintains a library of pre-built images documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/ruby:2.4.1

    working_directory: ~/repo

    steps:
      - checkout
      - run: node --version
      - run: node -e "console.log('Hello World')"
      # - run: ruby --version

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Testing workspace
      - run: mkdir -p roys_workspace
      - run: echo "Trying out workspaces" > roys_workspace/echo-output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: roys_workspace
          # Must be relative path from root
          paths:
            - echo-output

  test-the-app:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn test

      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: roys_workspace

      - run: |
          if [[ $(cat roys_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi

workflows:
  version: 2
  buid-and-test:
    jobs:
      - build-the-app
      - test-the-app
